### ISSUE TITLE
Assertion Error in Novel Category Evaluation Due to Category Number Mismatch

### ISSUE THREAD

**Issue by nightgoodl** [UVA-Computer-Vision-Lab/ovmono3d#18]
When evaluating novel categories using `do_test(cfg, model, mode='novel')`, an assertion error occurs in `omni3d_evaluation.py`:
```python
AssertionError: assert len(class_names) == precisions.shape[2]
```
This error indicates a mismatch between the number of configured categories and the actual prediction categories during evaluation.

## Current Implementation
1. The evaluation process is called separately for novel and base categories:
```python
do_test(cfg, model, mode='novel')
do_test(cfg, model, mode='base')
```

2. In `omni3d_evaluation.py`, the evaluation uses all category names regardless of mode:
```python
res = self._derive_omni_results(
    evals[mode],
    task,
    mode,
    class_names=self._metadata.get("thing_classes"),  # Using all categories
)
```

## Problem
When evaluating novel categories:
- `class_names` contains all categories (base + novel)
- But `precisions.shape[2]` only contains novel categories
- This mismatch triggers the assertion error

Any suggestions would be greatly appreciated.

**Comment by nightgoodl** [comment]
I am currently testing this on ARKitScenes only
1. In dataset loading (`datasets.py`):
   - When loading novel datasets, all category mappings are loaded from `configs/category_meta.json`
   - For `ARKitScenes_test_novel`, this includes mappings for all possible categories

2. In evaluation (`builtin.py`):
   - `get_omni3d_categories()` for `ARKitScenes_test_novel` only returns one category: `{'fireplace'}`（because your settings in `builtin.py`）
   - This creates a mismatch between loaded categories and categories used for evaluation

**Comment by nightgoodl** [comment]
And I am confused why the novel category is included in both the ARKitScenes training set and the validation set. In my understanding, it should not exist.

**Comment by nightgoodl** [comment]
I think I may have setup my SFP.yaml file incorrectly 
```
DATASETS:
  TRAIN: ('ARKitScenes_train', 'ARKitScenes_val')
  TEST: ('ARKitScenes_test', 'ARKitScenes_test_novel') 
  CATEGORY_NAMES: ("toilet", "fireplace", "table", "bed", "sofa", "television", "refrigerator", "chair", "cabinet", "stove", "oven", "shelves", "sink", "machine", "bathtub")
```
I would be grateful for any suggestions you have
